service: s3-upload-postprocess-lambda

frameworkVersion: ">=1.1.0 <2.0.0"

custom:
  bucket: pythondatademo123

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  postprocess:
    handler: source/postprocessor.file_handler
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .txt

  create:
    handler: source/create.s3Upload
    events:
      - http:
          path: s3Upload
          method: post
          cors: true